import bcrypt from 'bcryptjs';

export const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      role: 'user',
      root: true,
      avatart:
        'https://res.cloudinary.com/smartfanis/image/upload/v1631895168/avatar/AvatarMaker_illwbk.png',
    },
    {
      name: 'Jane',
      email: 'faisallarai@gmail.com',
      password: bcrypt.hashSync('123456'),
      role: 'user',
      root: false,
      avatar:
        'https://res.cloudinary.com/smartfanis/image/upload/v1631895168/avatar/AvatarMaker_illwbk.png',
    },
  ],
  products: [
    {
      name: 'Milo 3 in one',
      slug: 'milo-3-in-one',
      category: 'Beverages',
      image: '/image/milo-3-in-one.jpg',
      price: 1,
      brand: 'Milo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Milo 3 in one',
    },
    {
      name: 'Frytol 1 ltr',
      slug: 'frytol-1-ltr',
      category: 'Oil',
      image: '/image/frytol-1.jpg',
      price: 10,
      brand: 'Frytol',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Frytol 1 ltr',
    },
    {
      name: 'Unoli 1 ltr',
      slug: 'unoli-1-ltr',
      category: 'Oil',
      image: '/image/unoli-1.jpg',
      price: 2,
      brand: 'Unoli',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Unoli 1 ltr',
    },
    {
      name: 'Cerelac fruit',
      slug: 'cerelac-fruit',
      category: 'Beverages',
      image: '/image/cerelac-fruit.jpg',
      price: 1.5,
      brand: 'Cerelac',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Cerelac fruit',
    },
    {
      name: 'Cerelac biscuit',
      slug: 'cerelac-biscuit',
      category: 'Beverages',
      image: '/image/cerelac-biscuit.jpg',
      price: 17.5,
      brand: 'Cerelac',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Cerelac biscuit',
    },
    {
      name: 'Yumvita wheat',
      slug: 'yumvita-wheat',
      title: 'Yumvita wheat',
      category: 'Beverages',
      images: [
        {
          public_id: 'grocery/retetertre',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1631895168/avatar/AvatarMaker_illwbk.png',
        },
      ],
      price: 15,
      brand: 'Yumvita',
      content: 'Yumvita',
      checked: true,
      inStock: 1,
      sold: 1,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Yumvita wheat',
    },
  ],
};
