import bcrypt from 'bcryptjs';

export const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      role: 'user',
      root: true,
      avatart:
        'https://res.cloudinary.com/smartfanis/image/upload/v1631895168/avatar/AvatarMaker_illwbk.png',
    },
    {
      name: 'Jane',
      email: 'faisallarai@gmail.com',
      password: bcrypt.hashSync('123456'),
      role: 'user',
      root: false,
      avatar:
        'https://res.cloudinary.com/smartfanis/image/upload/v1631895168/avatar/AvatarMaker_illwbk.png',
    },
  ],
  products: [
    {
      name: 'Milo tin 400g',
      slug: 'milo-tin-400g',
      title: 'Milo tin 400g',
      category: 'Beverages',
      images: [
        {
          public_id: 'grocery/milo_tin_400g_n1sn3p',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1632090489/grocery/milo_tin_400g_n1sn3p.jpg',
        },
      ],
      price: 15,
      brand: 'Milo',
      content: 'Milo tin 400g',
      checked: true,
      inStock: 1,
      sold: 1,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Milo 3 in one',
    },
    {
      name: 'Gino 210g sup',
      slug: 'gino-210g-sup',
      title: 'Gino 210g sup',
      category: 'Tomato Paste',
      images: [
        {
          public_id: 'grocery/gino_210g_sup_single_front_hz8efv',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1632090723/grocery/gino_210g_sup_single_front_hz8efv.jpg',
        },
        {
          public_id: 'grocery/gino_210g_sup_single_back_wdskgp',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1632090721/grocery/gino_210g_sup_single_back_wdskgp.jpg',
        },
      ],
      price: 4,
      brand: 'Gino',
      content: 'Gino 210g sup',
      checked: true,
      inStock: 10,
      sold: 1,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Gino 210g sup',
    },
    {
      name: 'Gino 70g pepper sup',
      slug: 'gino-70g-pepper-sup',
      title: 'Gino 70g pepper sup',
      category: 'Tomato Paste',
      images: [
        {
          public_id: 'grocery/gino_70_pepper_onion_box_top_mtqmsu',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1632091035/grocery/gino_70_pepper_onion_box_top_mtqmsu.jpg',
        },
        {
          public_id: 'grocery/gino_70_pepper_onion_box_side_huc08k',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1632091105/grocery/gino_70_pepper_onion_box_side_huc08k.jpg',
        },
        {
          public_id: 'grocery/gino_70g_pepper_strip_pbvkgw',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1632091045/grocery/gino_70g_pepper_strip_pbvkgw.jpg',
        },
        {
          public_id: 'grocery/gino_70_pepper_onion_box_front_ikdtpe',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1632091032/grocery/gino_70_pepper_onion_box_front_ikdtpe.jpg',
        },
      ],
      price: 37,
      brand: 'Gino',
      content: 'Gino 70g pepper sup',
      checked: true,
      inStock: 1,
      sold: 1,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Gino 70g pepper sup',
    },
    {
      name: 'Cerelac fruit',
      slug: 'cerelac-fruit',
      title: 'Cerelac fruit',
      category: 'Beverages',
      images: [
        {
          public_id: 'grocery/retetertre',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1631895168/avatar/AvatarMaker_illwbk.png',
        },
      ],
      price: 15,
      brand: 'Cerelac',
      content: 'Cerelac Fruit',
      checked: true,
      inStock: 1,
      sold: 1,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Cerelac Fruit',
    },
    {
      name: 'Cerelac biscuit',
      slug: 'cerelac-biscuit',
      title: 'Cerelac biscuit',
      category: 'Beverages',
      images: [
        {
          public_id: 'grocery/retetertre',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1631895168/avatar/AvatarMaker_illwbk.png',
        },
      ],
      price: 15,
      brand: 'Cerelac',
      content: 'Cerelac Biscuit',
      checked: true,
      inStock: 1,
      sold: 1,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Cerelac Biscuit',
    },
    {
      name: 'Yumvita wheat',
      slug: 'yumvita-wheat',
      title: 'Yumvita wheat',
      category: 'Beverages',
      images: [
        {
          public_id: 'grocery/retetertre',
          url: 'https://res.cloudinary.com/smartfanis/image/upload/v1631895168/avatar/AvatarMaker_illwbk.png',
        },
      ],
      price: 15,
      brand: 'Yumvita',
      content: 'Yumvita',
      checked: true,
      inStock: 1,
      sold: 1,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Yumvita wheat',
    },
  ],
};
